#!/bin/bash

############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

############################
# Variables
############################
# base root directory for all ng configurations
base_root_dir=~/.ng

# dotfile app source directory
dotfile_src=~/Documents/GitHub/dotfiles

# old dotfiles backup directory (timestamped)
timestamp=$(date +"%Y%m%d_%H%M%S")
old_dir=$base_root_dir/dotfiles/backup/$timestamp

# list of files/folders to symlink in homedir
files="aliases emacs gemrc gitconfig Guardfile local-aliases tmux.conf Xmodmap xinitrc zshrc zprofile"


############################
# Setup & Installation
############################

# install Tmux Plugin Manager if it doesn't exist
if [ ! -d ~/.tmux/plugins/tpm ]; then
    echo "🔍 TPM not found. Cloning TPM..."
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    echo "✅ TPM installed."
else
    echo "✅ TPM already installed."
fi


############################
# Directory Setup
############################

# create timestamped backup directory
echo -n "|_ Creating $old_dir for backup of any existing dotfiles ..."
mkdir -p $old_dir
echo "✅ done"


############################
# File Operations
############################

# change to the dotfiles directory
echo -n "🚀 Changing to the $dotfile_src directory ..."
cd $dotfile_src
echo "✅ done"

# move any existing dotfiles in homedir to backup directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
echo "🔗 Creating symlinks in home root..."
for file in $files; do
    mv ~/.$file $old_dir/ 2>/dev/null || true
    echo "|_ $(tput setaf 2)$file$(tput sgr0) -> $(tput setaf 5)~/.$file$(tput sgr0)"
    ln -s $dotfile_src/$file ~/.$file
done
echo "🎉 All symlinks created"
